<?php

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function tahoe_treetop_theme_suggestions_page_alter(array &$suggestions, array $variables) {

  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $content_type = $node->bundle();
    $suggestions[] = 'page__'.$content_type;
  }

  {
    // Add content type suggestions.
    if ($node = \Drupal::request()->attributes->get('node')) {
      array_splice($suggestions, 1, 0, 'page__node__' . $node->getType());
    }
  }
}